---
namespace: homestak
name: debian
version: 1.0.0
readme: README.md
authors:
  - homestak-iac <https://github.com/homestak-iac>
description: Debian-generic roles for system configuration
license_file: LICENSE
tags:
  - debian
  - linux
  - system
  - security
  - networking
repository: https://github.com/homestak-iac/ansible
documentation: https://github.com/homestak-iac/ansible
homepage: https://github.com/homestak-iac
issues: https://github.com/homestak-iac/ansible/issues
build_ignore:
  - "*.tar.gz"
